on:
  push:
    branches: master
jobs:
  _:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: Run the workflow
       run: |
        set -x
        # Erase the demo file and its history
        git filter-branch --force --index-filter "git rm --cached --ignore-unmatch demo.txt" --prune-empty --tag-name-filter cat -- --all
        # Recreate the demo file
        date -Iseconds >> demo.txt
        git add demo.text
        git commit -m "Update the demo value"
        git push
